# automa-o-prenchimento-taabela-excel
criei uma automação onde pega valores de uma tabela e o coloca em outra tabela, para um bom funcionamento,deve-se colocar na mesma ordem os dois valores.
import pyautogui
import time
import pandas as pd
import win32com.client as win32
#  mandar um alerta avisando que é pra clicar na primeira celula dos valores a serem colados
pyautogui.alert('Clique na primeira celula do canto superior esquerdo da tabela que vai ser preenchida.')
pyautogui.alert('vá para a tabela que contem os dados e verifique se todos os valores numerico ja etão no formato de numeros')
pyautogui.alert('Em seguida: \nClique novamente na primeira celula da coluna que contem os dados a serem inseridos')
pyautogui.alert('Em seguida: \nvolte para o compilador der um clique no compilador e clique no OK aqui embaixo a direita!')
pyautogui.hotkey('alt', 'tab')
time.sleep(1)
#  formatacao de valores
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.hotkey('down')
pyautogui.hotkey('ctrl','v')

pyautogui.hotkey('ctrl','up')
pyautogui.press('down')
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')

pyautogui.press('left')
pyautogui.hotkey('ctrl','up')
pyautogui.press('down',presses=2)
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.press('tab',presses=2)
pyautogui.hotkey('ctrl','v')

pyautogui.press('left',presses=2)
pyautogui.hotkey('ctrl','up')
pyautogui.press('down',presses=3)
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.press('tab',presses=3)
pyautogui.hotkey('ctrl','v')

pyautogui.press('left',presses=3)
pyautogui.hotkey('ctrl','up')
pyautogui.press('down',presses=4)
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.press('tab',presses=4)
pyautogui.hotkey('ctrl','v')

pyautogui.press('left',presses=4)
pyautogui.hotkey('ctrl','up')
pyautogui.press('down',presses=5)
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.press('tab',presses=5)
pyautogui.hotkey('ctrl','v')

pyautogui.press('left',presses=5)
pyautogui.hotkey('ctrl','up')
pyautogui.press('down',presses=6)
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.press('tab',presses=6)
pyautogui.hotkey('ctrl','v')

pyautogui.press('left',presses=6)
pyautogui.hotkey('ctrl','up')
pyautogui.press('down',presses=7)
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.press('tab',presses=7)
pyautogui.hotkey('ctrl','v')

pyautogui.press('left',presses=7)
pyautogui.hotkey('ctrl','up')
pyautogui.press('down',presses=8)
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.press('tab',presses=8)
pyautogui.hotkey('ctrl','v')

pyautogui.press('left',presses=8)
pyautogui.hotkey('ctrl','up')
pyautogui.press('down',presses=9)
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('ctrl','down')
pyautogui.press('tab',presses=9)
pyautogui.hotkey('ctrl','v')
pyautogui.hotkey('ctrl','left')
#  selecionar o primeiro campo e clicar ctrl+c
pyautogui.hotkey('ctrl','c')
time.sleep(0.5)
#  trocar de janela e clicar ctrl+v
pyautogui.keyDown('alt')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.keyUp('alt')
pyautogui.press('right')
pyautogui.hotkey('ctrl','down')
pyautogui.press('down')
pyautogui.hotkey('ctrl','v')
#  trocar de janela andar uma celula pro lado e clicar ctrl+c
time.sleep(0.25)
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','c')
#  trocar de janela  andar uma pro lado e clicar ctrl+v
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')
#  trocar de janela andar mais uma pro lado e clicar ctrl+c
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','c')
#  trocar de janela andar uma pro lado e clicar ctrl+v
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')
#  trocar de janela andar uma pro lado e clicar ctrl+c
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','c')
#  trocar de janela andar três casas para o lado e clicar ctrl+v
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')
#  trocar de janela andar uma casa e clicar ctrl+c
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','c')
#  trocar de janela andar uma casa e clicar ctrl+v
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')
#  trocar e janela andar uma casa e clicar ctrl+c
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','c')
#  trocar de janela andar quatro casas e clicar ctrl+v
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')
#  trocar de janela andar uma casa pro lado e clicar ctrl+c
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','c')
#  trocar de janela andar uma casa pro lado e clicar ctrl+v
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')
#  trocar de janela andar uma casa pro lado e clicar ctrl+c
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','c')
#  trocar de janela andar uma casa pro lado e clicar ctrl+v
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')
#  trocar de janela andar uma casa pro lado e clicar ctrl+c
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','c')
#  trocar de janela andar uma casa pro lado e clicar ctrl+v
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')
#  trocar de janela andar uma casa pro lado e clicar ctrl+c
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.hotkey('ctrl','c')
#  trocar de janela andar onze casas pro lado e clicar ctrl+v
pyautogui.hotkey('alt', 'tab')
time.sleep(0.25)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.hotkey('ctrl','v')


pyautogui.press('left')
pyautogui.write('=soma')
pyautogui.press('tab')
pyautogui.press('left')
pyautogui.press('left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.hotkey('shift','left')
pyautogui.press('enter')

pyautogui.alert('Uma parte da funcao Soma ja está pronta apenas coloque a celula limite do calculo para concluir 100%')
